crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from core import views

# Rotas principais
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", login_required(TemplateView.as_view(template_name='index.html')), name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("login/submit", views.submit_login, name="submit_login"),
    path("customer/", include("customer.urls"))
]

customer/urls.py
from django.urls import path
from .views import (
    CustomerListView,
    CustomerCreateView, 
    CustomerUpdateView, 
    CustomerDeleteView
)
from django.contrib.auth.decorators import login_required

app_name = "customer"

# Rotas do customer
urlpatterns = [
    path("list/", login_required(CustomerListView.as_view()), name="customer-list"),
    path("create/", login_required(CustomerCreateView.as_view()), name="customer-create"),
    path("<int:id>/", login_required(CustomerUpdateView.as_view()), name="customer-update"),
    path("<int:id>/delete/", login_required(CustomerDeleteView.as_view()), name="customer-delete")
]

core/models.py
from django.db import models

# Create your models here.

customer/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Customer(models.Model):
    # Cria tabela de clientes
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    birth_date = models.DateField()
    area_code = models.CharField(max_length=3)
    phone_number = models.CharField(max_length=9)
    country = models.CharField(max_length=30)
    state = models.CharField(max_length=30)
    city = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    # Retorna nome e sobrenome quando a classe é chamada
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    # Retorna o número de telefone completo quando a função é chamado
    def get_full_phone_number(self):
        return f"({self.area_code}) {self.phone_number}"
    
    # Retorna nome e sobrenome quando a função é chamada
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"
    
    # Retorna cidade - estado quando a função é chamada
    def get_full_city(self):
        return f"{self.city} - {self.state}"
    
    # Retorna os dados do cliente
    def get_absolute_url(self):
        return reverse("customer:customer-update", kwargs={"id": self.id})
    
    # Deleta um cliente do banco
    def get_delete_url(self):
        return reverse("customer:customer-delete", kwargs={"id": self.id})
    
    # Define o nome da tabela
    class Meta:
        db_table = "costumer"

customer/forms.py
from django import forms
from .models import Customer

# Define o input para o tipo date
class DateInput(forms.DateInput):
    input_type = "date"

# Cria um formulário para cadastro de novos clientes
class CustomerForm(forms.ModelForm):

    # Campos de nome e sobrenome
    first_name = forms.CharField(
        label="Nome",
        error_messages={"max_lenght": "O nome não pode conter mais de 30 caracteres"}
        )

    last_name = forms.CharField(
        label="Sobrenome",
        error_messages={"max_lenght": "O sobrenome não pode conter mais de 50 caracteres"}
        )

    # Email
    email = forms.EmailField(label="Email")

    # Data de nascimento
    birth_date = forms.DateField(label="Nascimento", widget=DateInput())

    # DDD e telefone com regex para validar
    area_code = forms.RegexField(
        label="DDD",
        regex=r"^\+?1?[0-9]{2}",
        error_messages={"invalid": "Número de DDD inválido"}
        )

    phone_number = forms.RegexField(
        label="Telefone",
        regex=r"^\+?1?[0-9]{8,9}",
        error_messages={"invalid": "Número de telefone inválido"}
        )

    # País, estado e cidade
    country = forms.CharField(label="País")
    state = forms.CharField(label="Estado")
    city = forms.CharField(label="Cidade")

    # Define o model da classe e os campos do formulário
    class Meta:
        model = Customer
        fields = (
                "first_name", 
                "last_name", 
                "email", 
                "birth_date", 
                "area_code", 
                "phone_number", 
                "country", 
                "state", 
                "city"
        )

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import (
authenticate, 
login as app_login,
logout as app_logout
)
from django.contrib import messages
# Create your views here.

# View para a página de login
def login(request):
    return render(request, "login.html")

# Valida o usuário para o login
def submit_login(request):
    if request.POST:
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user:
            app_login(request, user)
            return redirect("index")
        else:
            messages.error(request, "Usuário/Senha inválidos")

    return redirect("index")

# Função de logout
def logout(request):
    app_logout(request)
    return redirect("login")

customer/views.py
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from .models import Customer
from .forms import CustomerForm
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.db.models import Q

# Cria uma listview dos clientes
class CustomerListView(ListView):
    template_name = "customer/customer_list.html"    
    paginate_by = 5 # Paginação de 5 itens por página
    model = Customer # models.py
    
    # Função para busca
    def get_queryset(self):
        name = self.request.GET.get("name")
        # Verifica se o usuário está tentando fazer uma busca
        if name:
            # Busca os clientes por nome e/ou sobrenome
            object_list = self.model.objects.filter(
                Q(first_name__icontains=name) | Q(last_name__icontains=name)
                )
        else:
            # Quando não há busca
            object_list = self.model.objects.all()
        return object_list


# Cria a view da lista de clientes
class CustomerCreateView(CreateView):
    template_name = "customer/customer.html"
    form_class = CustomerForm

    def form_valid(self, form):
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse("customer:customer-list")
    
# Cria a view com os dados de um cliente
class CustomerUpdateView(UpdateView):
    template_name = "customer/customer.html"
    form_class = CustomerForm

    # Se o cliente não existir retorna erro 404
    def get_object(self):
        id = self.kwargs.get("id")
        return get_object_or_404(Customer, id=id)

    def form_valid(self, form):
        return super().form_valid(form)
    

    def get_success_url(self):
        return reverse("customer:customer-list")

# Recarrega a lista após deletar um cliente  
class CustomerDeleteView(DeleteView):

    # Se o cliente a ser deletado não existir retorna 404
    def get_object(self):
        id = self.kwargs.get("id")
        return get_object_or_404(Customer, id=id) 

    def get_success_url(self):
        return reverse("customer:customer-list")

core/templates/index.html
{% extends "model-page.html" %}

{% block content %}
   <h1>CRM</h1>
{% endblock %}

core/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/login.css' %}" >

</head>

<body class="d-flex flex-column">
  <div class="sidenav">
         <div class="login-main-text">
            <h2>CRM<br>Sistema de Gestão de Clientes</h2>            
         </div>
      </div>
      <div class="main">
         <div class="col-md-6 col-sm-12">
            <div class="login-form">
               <form action="submit", method="POST">{% csrf_token %}
                  <div class="form-group">
                     <label>Usuário</label>
                     <input type="text" class="form-control" placeholder="Usuário" name="username">
                  </div>
                  <div class="form-group">
                     <label>Senha</label>
                     <input type="password" class="form-control" placeholder="Senha" name="password">
                  </div>
                  {% if messages %}
                      {% for message in messages %}
                          <div class="alert alert-danger">{{ message }}</div>
                      {% endfor %}

                  {% endif %}
                  <button type="submit" class="btn btn-black">Login</button>
                 
               </form>
            </div>
         </div>
      </div>
</body>
</html>

core/templates/model-footer.html
<div class="container text-center">
    <small>Desenvolvido por <a href="https://github.com/wellrccity">Wellington Costa</a></small>
</div>

core/templates/model-header.html
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <a class="navbar-brand" href={% url 'index' %}>CRM</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'customer:customer-list' %}">Clientes</a>
        </li>
    </ul>
    <a style="position: absolute; top: 15%; right: 5%;" href="{% url "logout" %}"><button class="btn btn-outline-light">Sair</button></a>
    
</nav>

core/templates/model-page.html
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
        
    </head>

    <body class="d-flex flex-column">
        <header>
            {% include "model-header.html" %}
        </header>
        <main class="content" style="margin-top: 5%;">
            <div class="container">
                {% block content %}{% endblock %}
            </div>
        </main>
        <footer class="py-4 bg-dark text-white-50">
            {% include "model-footer.html" %}
        </footer>
    </body>
    <style>
        html {
            height: 100%;
          }
          
          body {
            display: flex;
            flex-direction: column;
            height: 100%;
            margin: 0;
          }
          
          main {
            flex: 1;
          }
          
          footer {
            margin-top: 10px;
            padding: 20px;
            position: relative;
            bottom: 0;
            width: 100%;
          }
    </style>
</html>

customer/templates/customer/customer.html
{% extends 'model-page.html' %}
{% load crispy_forms_tags %}
{% block content %}

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
    {% endif %}
     
    <form class="" action="" method="post">
        {% csrf_token %}

        {{ form|crispy }}

        <button type="submit" class="btn btn-primary">Salvar</button>

    </form>
{% endblock content %}

customer/templates/customer/customer_list.html
{% extends 'model-page.html' %}
{% block content %}
<h2 style="position: absolute;">Clientes</h2>
<a href="{% url "customer:customer-create" %}"><button type="button" class="btn btn-success" style="float: right; margin: 5px;">Adicionar</button></a>

<form>
    <div class="input-group mb-2">
        <input type="text" class="form-control" name="name" placeholder="Buscar por nome" aria-label="Buscar por nome" aria-describedby="basic-addon2">
        <div class="input-group-append">
            <button type="submit" class="btn btn-outline-primary">Buscar</button>
        </div>
    </div>


</form>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Cidade</th>
            <th>Telefone</th>
            <th>Email</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for customer in customer_list %}
        <tr>
            <td> <a href="{{customer.get_absolute_url}}">{{customer.get_full_name}}</a></td>
            <td>{{customer.get_full_city}}</td>
            <td>{{customer.get_full_phone_number}}</td>
            <td>{{customer.email}}</td>
            
            <td><button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modal-excluir">Excluir</button></td>

        </tr>

          <!-- Modal -->
        <div class="modal fade" id="modal-excluir" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Confirmação de exclusão</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                <h3 style="color: red;">Deseja realmente excluir "{{customer.get_full_name}}"?</h3>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                <form action="{{customer.get_delete_url}}" method="post">{%csrf_token%}
                <button type="submit" class="btn btn-danger">Excluir</button>
                </form>
                </div>
            </div>
            </div>
        </div>
        {% endfor %}
    </tbody>
</table>

<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Anterior</a></li>
        {% else %}
        <li class="page-item disabled" ><a class="page-link" href="#">Anterior</a></li>
        {% endif %}
        
        {% for object in page_obj.paginator.page_range %}
            
            {% if page_obj.number == forloop.counter %}
                <li class="page-item disabled"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
            {% endif %}

        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Próxima</a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link" href="#">Próxima</a></li>
        {% endif %}

    </ul>
  </nav>
  

{% endblock content %}